name: Tests

on:
  - push

jobs:
  test:
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    env:
      # Display must be available globally for linux to know where xvfb is
      DISPLAY: "99:0"
      QT_SELECT: "qt6"
      QT_QPA_PLATFORM: "offscreen"
      QT_DEBUG_PLUGINS: 1
      LIBGL_DEBUG: "verbose"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{matrix.python-version}}
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}
          cache: "pip"

      - name: Installing Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox tox-gh-actions coverage

      - name: Setup xvfb (Linux)
        uses: pyvista/setup-headless-display-action@v2
        with:
          qt: true

      - name: Test with tox (Linux)          
        if: runner.os == 'Linux'
        shell: bash
        run: |
          python -c "import platform; print(platform.system());"
          coverage run -m tox -e py${{matrix.python-version}}
      
  
      - name: Test Linting
        run: tox -e flake8
